import Header from "@/components/Header";
import Footer from "@/components/Footer";

const FullList = () => {
  const themes: string[] = [
    "Aadavark",
    "AdForest",
    "Adifier",
    "Admania",
    "Apress",
    "Babystreet",
    "Barberry",
    "Basel",
    "Bimber",
    "Blade",
    "Boombox",
    "Breek",
    "Bridge",
    "Broklyn",
    "Buzz",
    "Buzzy",
    "Caden",
    "Calafate",
    "Careefy",
    "CenaStore",
    "Cerato",
    "Cheerup",
    "Citybook",
    "Ciyashop",
    "Classiads",
    "Consulting",
    "Contentberg",
    "Cookandmeal",
    "Digiqole",
    "Eduma",
    "Elessi",
    "Enfold",
    "Fierzy",
    "Flatsome",
    "Flipmart",
    "Florian",
    "Freshio",
    "Froday",
    "Goliath",
    "Goodlife",
    "Goodnews",
    "Goya",
    "Greenmart",
    "Magplus",
    "Makali",
    "Market",
    "Martfury",
    "Maxshop",
    "Mayosis",
    "Mediacenter",
    "Merchandiser",
    "Metro",
    "Milano",
    "Mobimax",
    "Molla",
    "MRTailor",
    "MyMedi",
    "Neeon",
    "Neoton",
    "Newsblock",
    "Newsmag",
    "Newspaper",
    "Noucake",
    "Organic",
    "Oxygen",
    "Pangja",
    "Papr",
    "Peakshops",
    "Pinkmart",
    "Pixwell",
    "Plugins",
    "Pluto",
    "Poco",
    "Porto",
    "Presso",
    "Pressroom",
    "Printshop",
    "Puca",
    "Razzi",
    "Rehub",
    "Revo",
    "Rey",
    "Riode",
    "Sahifa",
    "Saxon",
    "Gridlove",
    "Groci",
    "Gutentype",
    "Henrik",
    "Herald",
    "Shopkeeper",
    "Shopme",
    "Shoppystore",
    "Smartic",
    "Smartmag",
    "Sober",
    "Soledad",
    "Squaretype",
    "Stockie",
    "Stockie",
    "Strolik",
    "Supro",
    "Techmarket",
    "The7",
    "TheLanger",
    "TheRetailer",
    "Thevoux",
    "Tokoo",
    "Tonda",
    "UDesign",
    "Valenti",
    "Vinkmag",
    "Woodmart",
    "Zeen",
    "Zoxnews",
    "Zoxpress",
    "Homey",
    "Hongo",
    "Hyperx",
    "Ibid",
    "Impreza",
    "Jannah",
    "Jevelin",
    "Jnews",
    "Jobmonster",
    "Johannes",
    "June",
    "JupiterX",
    "Kapee",
    "Kartpul",
    "Kicker",
    "Kidz",
    "Kingdom",
    "Konte",
    "LeArts",
    "Listingpro",
    "Locales",
  ];

  const pluginCategories: { title: string; items: string[] }[] = [
    {
      title: "Page Builders",
      items: [
        "WPBakery",
        "Elementor Pro",
        "Divi Builder",
        "Beaver Builder",
        "Thrive Themes Architect",
        "Oxygen",
        "KingComposer Pro",
        "Ultimate Addons for Elementor",
        "Ultimate Addons for WPBakery",
        "Ultimate Addons for Beaver Builder",
        "Essential Addons for Elementor",
        "JetElements for Elementor",
        "PowerPack Beaver Builder Addon",
        "Elementor Extras",
        "Happy Elementor Addons Pro",
        "Dynamic Content for Elementor",
        "The Plus Addons for Elementor",
        "JetEngine for Elementor",
        "Anywhere Elementor Pro",
        "Brizy Builder Pro",
        "PowerPack for Elementor",
        "Piotnet Addons for Elementor",
        "Element Pack for Elementor",
        "Unlimited Elements for Elementor",
        "Themify Builder",
        "Cornerstone Page Builder",
        "Livemesh Addons for Elementor",
        "All in One Addons for WPBakery",
        "Boosted Elements for Elementor",
        "Wallce Inline for Beaver Builder",
        "WooPack for Beaver Builder",
        "Unlimited Addons for Visual Composer",
        "Divi Mega Pro",
        "HT Mega Pro",
      ],
    },
    {
      title: "SEO Plugins",
      items: [
        "All-in-One SEO Pack Pro",
        "Schema Pro",
        "WPMU Dev SmartCrawl",
        "Interlinks Manager",
        "Premium SEO Pack",
        "Rankie Rank Tracker",
        "SNIP Structured Data",
        "SEOPress",
        "Permalink Manager Pro",
        "Schema Premium",
        "Hreflang Manager",
        "Simple Link Directory Pro",
        "Rich Snippets",
      ],
    },
    {
      title: "Performance Plugins",
      items: [
        "WP Rocket",
        "Smush Pro",
        "Swift Performance",
        "Divi Booster",
        "Perfmatters",
        "WP Fastest Cache",
        "Google Page Speed Image Optimizer",
        "WPMU Dev Hummingbird",
        "W3 Total Cache Pro",
        "Gonzales Speed Up WordPress",
      ],
    },
    {
      title: "Design Plugins",
      items: [
        "Slider Revolution",
        "Essential Grid Gallery",
        "Layered Popups",
        "Smart Slider 3 Pro",
        "Instagram Feed Pro",
        "WP AMP",
        "Content Views Pro",
        "UberMenu",
        "LayerSlider",
        "CSS Hero Pro",
        "Yottie Youtube Gallery",
        "WP Media Boxes",
        "Astra Pro Sites",
        "WP Notification Bar",
        "The Grid",
        "Final Tiles WordPress Gallery",
        "Yellow Pencil",
        "WP Mega Menu Pro",
        "WPtouch Pro",
        "Quadmenu",
        "Master Popups",
        "Max Mega Menu Pro",
        "Loginpress Pro",
        "Global Gallery",
        "Hero Menu",
        "Jet Popup",
        "JetMenu",
        "Loftloader Pro",
        "Media Grid",
        "Meta Slider Pro",
        "Testimonials Slider",
        "WordPress Pricing Table",
        "Easy Side Tab Pro",
        "Cool Timeline Pro",
        "Groovy Mega Menu",
        "Slick Menu",
        "Apex Notification Bar",
        "Modula Pro",
        "Quebly Pro",
        "TapTap Super Mobile Menu",
        "Ultra WordPress Admin Theme",
        "WPShapere WordPress Admin Theme",
        "Superfly Responsive Menu",
      ],
    },
    {
      title: "Analytic Plugins",
      items: [
        "PixelYourSite Pro",
        "PixelYourSite Super Pack",
        "Advanced WooCommerce Reporting",
        "WooCommerce Google Analytics",
        "WPMU Dev Google Analytics Plus",
        "WPMU Dev Beehive Pro",
        "Actionable Google Analytics for WooCommerce",
        "Bookly Pro",
        "Bookly Pro Add-on",
        "Eventon",
        "Eventon Tickets Add-on",
        "Amelia Booking System",
        "Events Calendar Pro",
        "Pinpoint Booking System",
        "Modern Events Calendar",
        "FooEvents for WooCommerce",
        "Calendarista Premium Edition",
        "Fat Events",
        "LatePoint Booking & Reservation",
        "Bookmify",
        "FAT Services Booking",
      ],
    },
    {
      title: "Other Plugins",
      items: [
        "AffiliateWP",
        "Gravity Forms",
        "Gravity Forms Addons",
        "Gravity Perks for Gravity Forms",
        "Gravity Forms Styles Pro Add-on",
        "Ninja Popups",
        "WP User Frontend Pro",
        "WP All Import Pro",
        "WP All Export Pro",
        "Ajax Search Pro",
        "FAST Suport Ticket",
        "WPML",
        "WPML String Translation",
        "WPML Translation Management Addon",
        "WP Review Pro",
        "Polylang Pro",
        "Directories Pro",
        "WP Google Maps",
        "Directory Pro",
        "Use-Your-Drive Google Drive Plugin",
        "Out-Of-The-Box Dropbox Plugin",
        "Share-One-Drive OneDrive Plugin",
        "Pretty Links",
        "WP Forms",
        "WP Forms Addons",
        "Thrive Apprentice",
        "Thrive Quiz Builder",
        "Thrive Leads",
        "Thrive Optimize",
        "Thrive Clever Widgets",
        "Thrive Headline Optimizer",
        "Thrive Ultimatum",
        "Thrive Ovation",
        "Disable Admin Notices",
        "Dokan Pro",
        "ADS Pro Plugin",
        "LearnDash LMS",
        "Content Egg",
        "WP Database Search and Replace",
        "Formidable Forms Pro",
        "Bloom Email Opt-In",
        "WP Media Folder",
        "WordPress Auto Spinner",
        "Convert Pro",
        "Mailster",
        "Advanced Google Maps Plugin",
        "WP Job Manager",
        "Youzer",
        "Ultimate Affiliate Pro",
        "User Role Editor Pro",
        "SearchWP",
        "FileBird",
        "YITH Amazon S3 Storage Premium",
        "Admin Columns Pro",
        "WPMU Dev Google Maps",
        "WPMU Dev Hustle",
        "Media Cleaner Pro",
        "MapSVG Interactive Vector",
        "Freelance Cockpit",
        "MailWizz Email Marketing",
        "Elite Video Player",
        "Coin Market Cap & Prices",
        "WP RSS Aggregator",
        "Mailpoet Premium",
        "Forminator Pro",
        "Super Forms",
        "SUMO Affiliates Pro",
        "Smart Notification",
        "Reactive Pro",
        "Web 2.0 Directory Plugin",
        "Asset Cleanup Pro",
        "Ninja Tables Pro",
        "Advanced Database Cleaner",
        "Client Portal for WordPress",
        "Share-one-Drive",
        "Quick Featured Images Pro",
        "Admin Menu Editor Pro",
        "Countdown Timer",
        "TotalPoll Pro",
        "Profile Builder Pro",
        "JetBlog",
        "JetSearch",
        "JetTricks",
        "JetBlocks",
        "JetTabs",
        "Jet Product Gallery for Elementor",
        "Jet Smart Filters",
        "FacetWP",
        "WPNotif SMS & WhatsApp Notifications",
        "User Extra Fields",
        "WP Offload Media Pro",
        "Digits Mobile Number Signup and Login",
        "Projecthuddle",
        "Advanced iFrame Pro",
        "wpDataTables",
        "MainWP + Extensions",
        "Lets Review",
        "Multi Rating Pro",
        "Uncanny Automator Pro",
        "WP Staging Pro",
        "BetterDocs Pro",
        "WP Scheduled Posts Pro",
        "BuddyBoss Platform Plugin",
        "Toolset Access",
        "Toolset Blocks",
        "Toolset Forms",
        "Toolset Layouts",
        "Toolset Module Manager",
        "Toolset Views",
        "Toolset WooCommerce Views",
        "Toolset Maps",
        "Toolset Framework Installer",
        "Toolset Types",
        "WP Mail SMTP Pro",
        "Memberpress",
        "WordPress Real Media Library",
        "Adning Advertising",
        "Emage for Elementor",
        "IconPress Pro",
        "Image Map Pro",
        "HappyForms Pro",
        "TastyLinks",
        "WPFomify",
        "GeneratePress Premium Addons",
        "Live Search and Custom Fields",
        "WHMPress WHMCS Integration for WP",
        "Reviewer WordPress Plugin",
        "Support Board",
        "Projectopia",
        "Blog Designer Pro",
        "QuForm",
        "Live Search and Custom Fields",
        "ConvertPlus Popup",
        "Everest Google Places Reviews",
        "iPanorama 360",
        "Deactivate Plugins per Page",
        "Divi Supreme Pro",
        "Cookie Plus",
        "Calendarize it!",
        "File Manager Plugin For WordPress",
        "Mailster",
        "Premium URL Shortener",
        "Sticky Html5 Music Player",
        "TotalContest Pro",
        "WordPress Real Physical Media",
        "WP Project Manager Pro",
        "Quizmaker",
        "WP Content Crawler",
        "Contact Us All-in-One Button",
        "UberChart",
        "Scroll Magic",
        "Nex-Forms",
        "Chatbot for WordPress",
        "WP File Download",
        "ARforms",
        "Formcraft",
        "Buzzfeed Quiz Builder",
        "WordPress GDPR",
        "PageLoader",
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-12">
        <h1 className="text-3xl lg:text-5xl font-bold text-foreground mb-8">
          Full Themes and Plugins List
        </h1>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">Themes</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {themes.map((name, idx) => (
              <div
                key={`${name}-${idx}`}
                className="rounded-md border bg-card text-card-foreground px-4 py-2"
              >
                {name}
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-2">Plugins</h2>
          {pluginCategories.map((category) => (
            <div key={category.title} className="mb-8">
              <h3 className="text-xl font-semibold mb-3">{category.title}</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                {category.items.map((name, idx) => (
                  <div
                    key={`${category.title}-${name}-${idx}`}
                    className="rounded-md border bg-card text-card-foreground px-4 py-2"
                  >
                    {name}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default FullList;